name: Run tests and upload coverage

on:
  pull_request:
      branches: [main]
  workflow_dispatch:
    inputs:
      run-tests:
        description: 'Run tests'
        default: 'true'
        required: false

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Node
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npx jest --coverage

      - name: Run tests
        run: npx jest --coverage

